module.exports = {
  apps: [
    {
      name: "screenpipe",
      script: "screenpipe",
      args: "--enable-realtime-vision",
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 5000,
      error_file: "~/.pm2/logs/screenpipe-error.log",
      out_file: "~/.pm2/logs/screenpipe-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "ollama",
      script: "ollama",
      args: "serve",
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 5000,
      error_file: "~/.pm2/logs/ollama-error.log",
      out_file: "~/.pm2/logs/ollama-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
    },
    {
      name: "livepipe-app",
      script: "bun",
      args: "run dev",
      cwd: process.env.HOME + "/.livepipe",
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 5000,
      error_file: "~/.pm2/logs/livepipe-app-error.log",
      out_file: "~/.pm2/logs/livepipe-app-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      env: {
        PORT: 3060,
        NODE_ENV: "development",
      },
    },
  ],
};
